# name: Cypress Cloud

# on:
#   workflow_dispatch:
#     inputs:
#       spec:
#         description: Run by command line
#         default: cypress/e2e/*

# jobs:
#   cypress-e2e-electron:
#     runs-on: ubuntu-latest
#     container:
#       image: cypress/browsers:node-22.16.0-chrome-136.0.7103.113-1-ff-138.0.4-edge-136.0.3240.76-1
#       options: --user 1001
#     steps:
#       - name: Get code
#         uses: actions/checkout@v4.2.2

#       # - name: Restore Yarn cache
#       #   uses: actions/cache@v4
#       #   with:
#       #     path:  |
#       #       ~/.cache/yarn
#       #       ~/Library/Caches/Yarn
#       #     Key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#       #     restore-keys: |
#       #       ${{ runner.os }}-yarn-

#       - name: Cypress run
#         uses: cypress-io/github-action@v6.5.0
#         with:
#           install-command: yarn install
#           browser: electron
#           record: true
#           group: UI Electron
#           spec: ${{ github.event.inputs.spec }}
#         env:
#           CYPRESS_RECORD_KEY: 0e66ca28-3fe2-4a59-91b9-eb821a467b4f
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   cypress-e2e-chrome:
#     # needs: cypress-e2e-electron
#     runs-on: ubuntu-latest
#     container:
#       image: cypress/browsers:node-22.16.0-chrome-136.0.7103.113-1-ff-138.0.4-edge-136.0.3240.76-1
#       options: --user 1001
#     steps:
#       - name: Get code
#         uses: actions/checkout@v4.2.2

#       - name: Cypress run
#         uses: cypress-io/github-action@v6.5.0
#         with:
#           install-command: yarn install
#           browser: chrome
#           record: true
#           group: UI Chrome
#           spec: ${{ github.event.inputs.spec }}
#         env:
#           CYPRESS_RECORD_KEY: 0e66ca28-3fe2-4a59-91b9-eb821a467b4f
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   cypress-e2e-firefox:
#     # needs: cypress-e2e-electron
#     runs-on: ubuntu-latest
#     container:
#       image: cypress/browsers:node-22.16.0-chrome-136.0.7103.113-1-ff-138.0.4-edge-136.0.3240.76-1
#       options: --user 1001
#     steps:
#       - name: Get code
#         uses: actions/checkout@v4.2.2

#       - name: Cypress run
#         uses: cypress-io/github-action@v6.5.0
#         with:
#           install-command: yarn install
#           browser: firefox
#           record: true
#           group: UI Firefox
#           spec: ${{ github.event.inputs.spec }}
#         env:
#           CYPRESS_RECORD_KEY: 0e66ca28-3fe2-4a59-91b9-eb821a467b4f
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, electron]
    container:
      image: cypress/browsers:node-22.16.0-chrome-136.0.7103.113-1-ff-138.0.4-edge-136.0.3240.76-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            ~/Library/Caches/Yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Restore Cypress cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: ${{ matrix.browser }}
          record: true
          group: UI - ${{ matrix.browser }}
          parallel: true
          ci-build-id: ${{ github.run_id }}-${{ matrix.browser }}
          spec: ${{ github.event.inputs.spec }}
          cache: none
        env:
          CYPRESS_RECORD_KEY: 0e66ca28-3fe2-4a59-91b9-eb821a467b4f
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            ~/Library/Caches/Yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Save Cypress cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
